name: Ethan Bennett
favicon: null
layout_spectrum: 0.9995807809755206
typography_spectrum: 0.31651485268957913
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0c0d11'
    - '#adbbd6'
    - '#fef6d2'
    - '#7b8086'
    - '#d89c82'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.805627689929679
  rhythmicContrast: 0.75
purpose: []
