name: Ethan Bennett
favicon: null
layout_spectrum: 0.9995807809755206
typography_spectrum: 0.31651485268957913
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.00550742750056088
  lightness: 0.12883803434669971
  saturation: 0.805627689929679
  rhythmicContrast: 0.33314241492189467
purpose: []
